# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: thsilva <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/10 11:15:32 by thsilva           #+#    #+#              #
#    Updated: 2018/11/10 11:21:40 by thsilva          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = srcs/*.c
NAME = eval_expr
FlAGS = -Wall -Werror -Wextra 

all:
	gcc $(FLAGS) -o $(NAME)

clean:
	rm -f *.o

fclean: clean
	rm -f $(NAME)

re:
	fclean all
