# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: thsilva <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/08 21:07:43 by thsilva           #+#    #+#              #
#    Updated: 2018/11/08 21:58:39 by thsilva          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = srcs/*.c
OBJS = *.o
NAME = ft_display_file

all: 
	gcc -o $(NAME) $(SRCS)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all
